name: Notify Slack on Push

on:
  push:
    branches:
      - main

jobs:
  summarize_and_notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install curl and jq
        run: sudo apt-get install curl jq -y

      - name: Fetch changes or current commit content
        id: fetch_changes
        run: |
          if git rev-parse HEAD~1 >/dev/null 2>&1; then
            git diff HEAD~1..HEAD > changes.txt
          else
            git show HEAD > changes.txt
          fi

      - name: Create a summary prompt from commit changes
        id: create_prompt
        run: |
          CONTENT=$(<changes.txt)
          echo "::set-output name=prompt::最新のコミットでの変更内容を要約してください。変更されたファイルの内容は以下のとおりです。$CONTENT"

      - name: Summarize commit changes with OpenAI GPT-4
        id: summarize
        run: |
          SUMMARY=$(curl -X POST -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" -H "Content-Type: application/json" -d '{"prompt": "'${{ steps.create_prompt.outputs.prompt }}'", "max_tokens": 150, "temperature": 0.5}' https://api.openai.com/v1/engines/gpt-4/completions | jq -r '.choices[0].text')
          echo "::set-output name=summary::$SUMMARY"

      - name: Send message to Slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          webhookUrl: ${{ secrets.SLACK_WEBHOOK_URL }}
          payload: |
            {
              "text": "中山航の本日の学習記録: ${{ steps.summarize.outputs.summary }}"
            }
