name: Notify Slack on Push

on:
  push:
    branches:
      - main

jobs:
  summarize_and_notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install curl and jq
        run: sudo apt-get install curl jq -y

      - name: Fetch commit messages
        id: fetch_commits
        run: |
          git log --pretty=format:"%s" HEAD~1..HEAD > commit_messages.txt

      - name: Read commit messages and create a summary prompt
        id: create_prompt
        run: |
          CONTENT=$(<commit_messages.txt)
          echo "::set-output name=prompt::本日の学習記録をコミットしたので、何について学習したかを要約してください。学習内容はマークダウン形式で記述しているので、タイトル(#、##)の情報を重要視すればいい要約ができるのではないかと思います。学習内容は以下です。$CONTENT"

      - name: Summarize commits with OpenAI GPT-4
        id: summarize
        run: |
          SUMMARY=$(curl -X POST -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" -H "Content-Type: application/json" -d '{"prompt": "'${{ steps.create_prompt.outputs.prompt }}'", "max_tokens": 150, "temperature": 0.5}' https://api.openai.com/v1/engines/gpt-4/completions | jq -r '.choices[0].text')
          echo "::set-output name=summary::$SUMMARY"

      - name: Send message to Slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          payload: '{"text": "中山航の本日の学習記録: ${{ steps.summarize.outputs.summary }}"}'
